### ISSUE TITLE
加载我们本地的url白屏，还没找到原因

### ISSUE THREAD

**Issue by qingweiSun** [wendux/WebViewJavascriptBridge#13]

**Comment by wendux** [comment]
可以先用系统webview 加载看看是否依然白屏

**Comment by qingweiSun** [comment]
这个我知道了。是settings.setAllowFileAccess(true);
就好了，但是首次调用的时候有时候他们拿不到回调

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: wendux <notifications@github.com>
发送时间: Thursday, March 22, 2018 9:57:45 PM
收件人: wendux/WebViewJavascriptBridge
抄送: qingweiSun; Author
主题: Re: [wendux/WebViewJavascriptBridge] 加载我们本地的url白屏，还没找到原因 (#13)


可以先用系统webview 加载看看是否依然白屏

―

**Comment by qingweiSun** [comment]
好了，解决了
