### ISSUE TITLE
Js通过addJavascriptInterface的方式与native通信，在4.4以下手机不会有安全问题么？

### ISSUE THREAD

**Issue by xq598359628** [wendux/WebViewJavascriptBridge#2]
如题

**Comment by wendux** [comment]
This method(addJavascriptInterface) can be used to allow JavaScript to control the host
     * application. This is a powerful feature, but also presents a security
     * risk for apps targeting {@link android.os.Build.VERSION_CODES#JELLY_BEAN} or earlier.
     * Apps that target a version later than JELLY_BEAN
     * are still vulnerable if the app runs on a device running Android earlier than 4.2.
     * The most secure way to use this method is to target JELLY_BEAN_MR1
     * and to ensure the method is called only when running on Android 4.2 or later.

**Comment by xq598359628** [comment]
JSbridge的存在不就是因为这个安全问题么?如果这样的话，那您这样修改岂不是没有多大的必要么

**Comment by wendux** [comment]
在minSdkVersion >=17时，还要兼容IOS的WebViewJavascriptBridge时，这个库就很有必要了啊。
