### ISSUE TITLE
想问下作者,这里这样的写法,是包含怎样的意思,我看这块没看懂

### ISSUE THREAD

**Issue by Vander-liu** [wendux/WebViewJavascriptBridge#20]
@Override
        public void onReceivedTouchIconUrl(WebView view, String url, boolean precomposed) {
            if (webChromeClient != null) {
                webChromeClient.onReceivedTouchIconUrl(view, url, precomposed);
            } else {
                super.onReceivedTouchIconUrl(view, url, precomposed);
            }
        }

        @Override
        public void onShowCustomView(View view, CustomViewCallback callback) {
            if (webChromeClient != null) {
                webChromeClient.onShowCustomView(view, callback);
            } else {
                super.onShowCustomView(view, callback);
            }
        }

        @TargetApi(Build.VERSION_CODES.ICE_CREAM_SANDWICH)
        public void onShowCustomView(View view, int requestedOrientation,
                                     CustomViewCallback callback) {
            if (webChromeClient != null) {
                webChromeClient.onShowCustomView(view, requestedOrientation, callback);
            } else {
                super.onShowCustomView(view, requestedOrientation, callback);
            }
        }

        @Override
        public void onHideCustomView() {
            if (webChromeClient != null) {
                webChromeClient.onHideCustomView();
            } else {
                super.onHideCustomView();
            }
        }

        @Override
        public boolean onCreateWindow(WebView view, boolean isDialog,
                                      boolean isUserGesture, Message resultMsg) {
            if (webChromeClient != null) {
                return webChromeClient.onCreateWindow(view, isDialog,
                        isUserGesture, resultMsg);
            }
            return super.onCreateWindow(view, isDialog, isUserGesture, resultMsg);
        }

**Comment by Vander-liu** [comment]
感觉复写出的WebChromeClient的这些方法,意义我不太清除,不如直接继承来,这样外部还可以根据您继承的WebChromeClient做一些扩展.

**Comment by Vander-liu** [comment]
现在我假设我要使用onReceiverTitle这个方法,如果直接引用您的第三方库,我除了直接修改源码,好像没有其他办法.

**Comment by wendux** [comment]
@Vander-liu 不用修改源码，webview怎么用，这个你就怎么用

**Comment by Vander-liu** [comment]
@wendux  感谢作者,刚刚又仔细的看了一遍. 看明白了,你内部设置的这一段是一层代理. 本来这次想用您的DsBridge的.但是前端已经按您这套的模式来了.改起来麻烦.
