### ISSUE TITLE
请问为何打开webview会默认弹出提示框

### ISSUE THREAD

**Issue by SunxiaoyaoHHL** [wendux/WebViewJavascriptBridge#22]
怎么关闭默认拦截提示框

**Comment by wendux** [comment]
弹出了什么？会不会是网页中js有调alert ？


 📱[From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by SunxiaoyaoHHL** [comment]
@wendux 是网页中有alert，webview自动拦截并弹出对话框了，我重写了下onJsAlert就好了，但是自动拦截alert感觉怪怪的
