### ISSUE TITLE
是基于什么原因调整最低版本为17呢？

### ISSUE THREAD

**Issue by kaxi4it** [wendux/WebViewJavascriptBridge#4]
如题

**Comment by wendux** [comment]
1. 安全原因，`WebView.addJavascriptInterface` 在4.2.2一下存在安全漏洞
2. 淘汰旧系统，目前大多数APP版本最低都已经是4.4了

**Comment by hxmeie** [comment]
这个框架本身就是为了避免安全问题的，原框架里就说了It provides safe and convenient way to call Java code from js and call js code from java.

**Comment by xq598359628** [comment]
然而我们的所有项目都还兼容到14...

**Comment by woniu0936** [comment]
我们这边，ios用的是https://github.com/marcuswestin/WebViewJavascriptBridge，请问我这边用你这个项目合适还是用https://github.com/wendux/DSBridge-Android合适？ @wendux

**Comment by wendux** [comment]
@woniu0936 不行，要用DSBridge的话， Android和IOS都要用。不同javascript bridge通信协议不一样，要不然就要写两份javascript 代码(接受不了)。  如果你们ios那边确定用[marcuswestin/WebViewJavascriptBridge](https://github.com/marcuswestin/WebViewJavascriptBridge) ，那android端使用本项目即可。

**Comment by woniu0936** [comment]
好的，感谢提供这个方便的库

**Comment by wendux** [comment]
现最低支持版本为11，4.2.2以下并没有使用`addJavascriptInterface`，而是通过其它方式传递消息，不存在安全性问题，请放心使用。
